### ISSUE TITLE
Merge does not yet support multiple Analysis objects

### ISSUE THREAD

**Issue by shrlck221** [shadow/oniontrace#2]
Hi,

I'm trying to parse all the oniontrace log files using oniontracetools, but once it's merging the results I'm getting this exception:

Exception: Merge does not yet support multiple Analysis objects from the same node (add multiple files from the same node to the same Analysis object before calling analyze instead)

I don't understand what it means "adding multiples files to the same analysis object".

Thanks!

**Comment by robgjansen** [comment]
I think that message is indicating that it detected in your search directory multiple log files from the same Shadow simulation node. 

oniontracetools is meant to parse all of the nodes' log files from a _single_ experiment at a time (ie one log file per node), but it's not meant to combine log files from multiple experiments into one (multiple log files per node) - when it detects the same node twice, data from the second log file would overwrite the data from the first. So instead of overwriting, it prints that error. 

Are you giving it a directory that contains results from multiple experiments? Ie the same node name has several log files?

If you want to force it to overwrite anyway (probably not what you want), you could comment out the safety check:
https://github.com/shadow/oniontrace/blob/bc26be3c4737a8a367a156f12bab2975cd811855/tools/oniontracetools/analysis.py#L98-L102

**Comment by shrlck221** [comment]
I didn't notice that the directory was containing log files from another experiment. After deleting them it executed just fine.

Thank you!

**Comment by robgjansen** [comment]
Great, so the logged exception did its job :)
